
trigger:
  - '*'

stages:

  - stage: Test
    jobs:
      - job: ARM
        pool: ARM
        container: alphaaqua/utcbuild:raspbian
        steps:
          - checkout: self
          - script: |
              pip3 install pytest-azurepipelines
              pytest
            displayName: ARM PyTest

      - job: Ubuntu
        pool:
          vmImage: 'ubuntu-latest'
        container: alphaaqua/utcbuild:ubuntu
        steps:
          - checkout: self
          - script: |
              pip3 install pytest-azurepipelines
              pytest
            displayName: Ubuntu PyTest


      - job: Windows
        pool:
          vmImage: 'windows-latest'
        container: alphaaqua/utcbuild:windows
        steps:
          - checkout: self
          - script: |
              pip3 install pytest-azurepipelines
              pytest
            displayName: Windows PyTest
