
trigger:
  - '*'

#pool:
#  vmImage: 'ubuntu-latest'
pool: ARM

stages:

  - stage: Test
    jobs:
      - job: PyTest
        container: alphaaqua/utcbuild:raspbian
        steps:
          - checkout: self

          - script: |
              pip install pytest-azurepipelines
              pytest
            displayName: 'pytest'
