
trigger:
  - '*'

stages:

  - stage: Test
    jobs:
      - job: PyTest
        pool: ARM
        container: alphaaqua/utcbuild:raspbian
        steps:
          - checkout: self

          - script: |
              pip install pytest-azurepipelines
              pytest
            displayName: 'pytest'
